Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"

    config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
    config.ssh.insert_key = false

    config.vm.network "public_network", ip: "10.191.186.243", bridge: "dm-783eee1b15c0"
    config.vm.provision "shell",
        run: "always",
        inline: "ifconfig enp0s8 10.191.186.243 netmask 255.0.0.0 up"

    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    config.vm.provision "file", source: "./html", destination: "~/html" 
    config.vm.provision "shell", path: "./entry.sh"
end