---
- name: "Create Disk Image"
  hosts: victim
  remote_user: vagrant
  become: yes
  become_user: root

  tasks:
  - name: "Run dd"
    shell: dd if=/dev/sda1 | gzip > /vagrant/filesystem.image.gz

