---
- name: "Create Disk Image"
  hosts: victim
  remote_user: vagrant
  become: yes
  become_user: root

  tasks:
  - name: "Run dd"
    shell: dd if=/dev/sda1 | gzip > /tmp/filesystem.image.gz

  - name: "Copy Image to Host"
    synchronize:
      mode: pull
      src: /tmp/filesystem.image.gz
      dest: /tmp/filesystem.image.gz
