---
- name: Copy logs
  hosts: victim
  remote_user: vagrant
  become: yes
  become_user: root


  tasks:
  - name: "Archive logs"
    archive: 
      path: "{{ log_path }}"
      dest: /tmp/logs.zip
      format: zip

  - name: "Copy logs out"
    fetch:
      src: /tmp/logs.zip
      dest: ./logs.zip
      flat: yes

  - name: "Delete logs temp file"
    file:
      state: absent
      path: /tmp/logs.zip      
